// <auto-generated />
using EliteWebTechAssignment.DAL.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EliteWebTechAssignment.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220804203602_tablenamechanged")]
    partial class tablenamechanged
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EliteWebTechAssignment.Domain.Models.CurrentSemEntityModel", b =>
                {
                    b.Property<int>("PkId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("currentSemester")
                        .HasColumnName("CurrentSemester");

                    b.Property<int>("studentId")
                        .HasColumnName("StudentId");

                    b.HasKey("PkId");

                    b.ToTable("CurrentSemesters");
                });

            modelBuilder.Entity("EliteWebTechAssignment.Domain.Models.IntakeEntityModel", b =>
                {
                    b.Property<int>("PkId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("intakeYear")
                        .HasColumnName("IntakeYear");

                    b.Property<int>("studentId")
                        .HasColumnName("StudentId");

                    b.HasKey("PkId");

                    b.ToTable("Intakes");
                });

            modelBuilder.Entity("EliteWebTechAssignment.Domain.Models.ProgrammeEntityModel", b =>
                {
                    b.Property<int>("programmeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ProgrammeId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("programmeName")
                        .IsRequired()
                        .HasColumnName("ProgrammeName");

                    b.HasKey("programmeId");

                    b.ToTable("Programmes");
                });

            modelBuilder.Entity("EliteWebTechAssignment.Domain.Models.StudentEntityModel", b =>
                {
                    b.Property<int>("studentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("StudentId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("collegeName")
                        .IsRequired()
                        .HasColumnName("College");

                    b.Property<int>("programmeId")
                        .HasColumnName("ProgrammeId");

                    b.Property<string>("studentName")
                        .IsRequired()
                        .HasColumnName("StudentName");

                    b.HasKey("studentId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("EliteWebTechAssignment.Domain.Models.SubjectEntityModel", b =>
                {
                    b.Property<int>("PkId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("programmeId")
                        .HasColumnName("ProgrammeId");

                    b.Property<string>("subjectName")
                        .HasColumnName("SubjectName");

                    b.HasKey("PkId");

                    b.ToTable("ProgrammeSubjects");
                });
#pragma warning restore 612, 618
        }
    }
}
